CREATE TABLE "USER" (
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"EMP_ID"	VARCHAR2(255)		NOT NULL,
	"PASSWORD"	VARCHAR2(16)		NOT NULL,
	"USER_NAME"	VARCHAR2(20)		NOT NULL,
	"BIRTHDAY"	NUMBER		NOT NULL,
	"PHONE_NUM"	VARCHAR2(11)		NOT NULL,
	"EMAIL"	VARCHAR2(255)		NULL,
	"ROLE"	VARCHAR2(255)		NOT NULL,
	"DEPARTMENT"	VARCHAR(255)		NULL,
	"PW_QUESTION"	VARCHAR2(255)		NOT NULL,
	"PW_ANSWER"	VARCHAR2(255)		NOT NULL,
	"NORMAL_ADDRESS"	VARCHAR(255)		NULL,
	"DETAIL_ADDRESS"	VARCHAR2(255)		NULL,
	"WITHDRAW_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"WITHDRAW_DATE"	VARCHAR2(20)		NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "USER"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "USER"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "USER"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "USER"."USER_NAME" IS '이름';

COMMENT ON COLUMN "USER"."BIRTHDAY" IS '생년월일';

COMMENT ON COLUMN "USER"."PHONE_NUM" IS '휴대전화';

COMMENT ON COLUMN "USER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "USER"."ROLE" IS '권한';

COMMENT ON COLUMN "USER"."DEPARTMENT" IS '부서';

COMMENT ON COLUMN "USER"."PW_QUESTION" IS '비밀번호찾기질문';

COMMENT ON COLUMN "USER"."PW_ANSWER" IS '비밀번호찾기답변';

COMMENT ON COLUMN "USER"."NORMAL_ADDRESS" IS '기본주소';

COMMENT ON COLUMN "USER"."DETAIL_ADDRESS" IS '상세주소';

COMMENT ON COLUMN "USER"."WITHDRAW_YN" IS '탈퇴여부';

COMMENT ON COLUMN "USER"."WITHDRAW_DATE" IS '탈퇴일시';

COMMENT ON COLUMN "USER"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "USER"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "FREE_BOARD" (
	"FREE_BOARD_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"LIKES"	NUMBER	DEFAULT 0	NULL,
	"CONTENT"	CLOB		NOT NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "FREE_BOARD"."FREE_BOARD_ID" IS '자유게시판번호';

COMMENT ON COLUMN "FREE_BOARD"."USER_ID" IS '작성자';

COMMENT ON COLUMN "FREE_BOARD"."LIKES" IS '좋아요';

COMMENT ON COLUMN "FREE_BOARD"."CONTENT" IS '내용';

COMMENT ON COLUMN "FREE_BOARD"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "FREE_BOARD"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "FREE_BOARD_COMMENT" (
	"FREE_BOARD_COMMENT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"FREE_BOARD_ID"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"SECRET_COMMENT_YN"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL,
	"CATEGORY"	VARCHAR(255)	DEFAULT '일반'	NOT NULL
);

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."FREE_BOARD_COMMENT_ID" IS '자유게시판댓글ID';

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."USER_ID" IS '작성자';

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."FREE_BOARD_ID" IS '자유게시판번호';

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."SECRET_COMMENT_YN" IS '비밀댓글유무';

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."UPDATE_TIME" IS '정보수정시간';

COMMENT ON COLUMN "FREE_BOARD_COMMENT"."CATEGORY" IS '카테고리';

CREATE TABLE "FREE_BOARD_REPORT" (
	"REPORT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"FREE_BOARD_ID"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(255)		NOT NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "FREE_BOARD_REPORT"."REPORT_ID" IS '신고번호';

COMMENT ON COLUMN "FREE_BOARD_REPORT"."USER_ID" IS '신고자';

COMMENT ON COLUMN "FREE_BOARD_REPORT"."FREE_BOARD_ID" IS '신고당한게시글';

COMMENT ON COLUMN "FREE_BOARD_REPORT"."CONTENT" IS '신고내용';

COMMENT ON COLUMN "FREE_BOARD_REPORT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "FREE_BOARD_REPORT"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "COMPLAINT_BOARD" (
	"COMPLAINT_BOARD_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"LIKES"	NUMBER	DEFAULT 0	NULL,
	"CONTENT"	CLOB		NOT NULL,
	"STATUS"	VARCHAR(255)	DEFAULT '확인중'	NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "COMPLAINT_BOARD"."COMPLAINT_BOARD_ID" IS '건의게시판번호';

COMMENT ON COLUMN "COMPLAINT_BOARD"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "COMPLAINT_BOARD"."LIKES" IS '좋아요';

COMMENT ON COLUMN "COMPLAINT_BOARD"."CONTENT" IS '내용';

COMMENT ON COLUMN "COMPLAINT_BOARD"."STATUS" IS '건의게시판상태, 확인중, 확인완료';

COMMENT ON COLUMN "COMPLAINT_BOARD"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "COMPLAINT_BOARD"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "DEPARTMENT_BOARD" (
	"DEPT_BOARD_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"DEPT_ID"	NUMBER		NOT NULL,
	"LIKES"	NUMBER	DEFAULT 0	NULL,
	"CONTENT"	CLOB		NOT NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "DEPARTMENT_BOARD"."DEPT_BOARD_ID" IS '부서게시판번호';

COMMENT ON COLUMN "DEPARTMENT_BOARD"."USER_ID" IS '작성자';

COMMENT ON COLUMN "DEPARTMENT_BOARD"."DEPT_ID" IS '부서번호';

COMMENT ON COLUMN "DEPARTMENT_BOARD"."LIKES" IS '좋아요';

COMMENT ON COLUMN "DEPARTMENT_BOARD"."CONTENT" IS '내용';

COMMENT ON COLUMN "DEPARTMENT_BOARD"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "DEPARTMENT_BOARD"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "DEPARTMENT" (
	"DEPT_ID"	NUMBER		NOT NULL,
	"DEPT_NAME"	VARCHAR(255)		NOT NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "DEPARTMENT"."DEPT_ID" IS '부서번호';

COMMENT ON COLUMN "DEPARTMENT"."DEPT_NAME" IS '부서이름';

COMMENT ON COLUMN "DEPARTMENT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "DEPARTMENT"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "COMPLAINT_BOARD_COMMENT" (
	"FREE_BOARD_COMMENT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"COMPLAINT_BOARD_ID"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "COMPLAINT_BOARD_COMMENT"."FREE_BOARD_COMMENT_ID" IS '자유게시판댓글ID';

COMMENT ON COLUMN "COMPLAINT_BOARD_COMMENT"."USER_ID" IS '작성자';

COMMENT ON COLUMN "COMPLAINT_BOARD_COMMENT"."COMPLAINT_BOARD_ID" IS '건의게시판번호';

COMMENT ON COLUMN "COMPLAINT_BOARD_COMMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "COMPLAINT_BOARD_COMMENT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "COMPLAINT_BOARD_COMMENT"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "DEPT_BOARD_COMMENT" (
	"DEPT_BOARD_COMMENT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"DEPT_BOARD_ID"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"SECRET_COMMENT_YN"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "DEPT_BOARD_COMMENT"."DEPT_BOARD_COMMENT_ID" IS '자유게시판댓글ID';

COMMENT ON COLUMN "DEPT_BOARD_COMMENT"."USER_ID" IS '작성자';

COMMENT ON COLUMN "DEPT_BOARD_COMMENT"."DEPT_BOARD_ID" IS '부서게시판번호';

COMMENT ON COLUMN "DEPT_BOARD_COMMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "DEPT_BOARD_COMMENT"."SECRET_COMMENT_YN" IS '비밀댓글유무';

COMMENT ON COLUMN "DEPT_BOARD_COMMENT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "DEPT_BOARD_COMMENT"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "CLUB_BOARD" (
	"CLUB_BOARD_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"LIKE"	NUMBER	DEFAULT 0	NULL,
	"CONTENT"	CLOB		NOT NULL,
	"LOCATION"	VARCHAR2(255)		NULL,
	"ADDRESS"	VARCHAR2(255)		NULL,
	"MAX_QUOTA"	NUMBER	DEFAULT 0	NULL,
	"MIN_QUOTA"	NUMBER	DEFAULT 0	NULL,
	"PARTICIPATION_FEE"	NUMBER	DEFAULT 0	NULL,
	"START_TIME"	VARCHAR2(20)		NOT NULL,
	"END_TIME"	VARCHAR2(20)		NOT NULL,
	"SEX"	VARCHAR2(255)	DEFAULT '남자'	NULL,
	"PEOPLES_MATCH"	VARCHAR2(255)	DEFAULT '미정'	NULL,
	"MATCH_FORM"	VARCHAR2(255)	DEFAULT '미정'	NULL,
	"MATERIAL"	VARCHAR2(255)	DEFAULT '없음'	NULL,
	"RECRUITMENT_DEADLINE"	VARCHAR2(20)		NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "CLUB_BOARD"."CLUB_BOARD_ID" IS '동아리게시판번호';

COMMENT ON COLUMN "CLUB_BOARD"."USER_ID" IS '방장';

COMMENT ON COLUMN "CLUB_BOARD"."LIKE" IS '좋아요';

COMMENT ON COLUMN "CLUB_BOARD"."CONTENT" IS '내용';

COMMENT ON COLUMN "CLUB_BOARD"."LOCATION" IS '장소명';

COMMENT ON COLUMN "CLUB_BOARD"."MAX_QUOTA" IS '최대인원';

COMMENT ON COLUMN "CLUB_BOARD"."MIN_QUOTA" IS '최소인원';

COMMENT ON COLUMN "CLUB_BOARD"."PARTICIPATION_FEE" IS '참가비';

COMMENT ON COLUMN "CLUB_BOARD"."START_TIME" IS '활동시작시간';

COMMENT ON COLUMN "CLUB_BOARD"."END_TIME" IS '활동종료시간';

COMMENT ON COLUMN "CLUB_BOARD"."SEX" IS '성별';

COMMENT ON COLUMN "CLUB_BOARD"."PEOPLES_MATCH" IS '매치인원수';

COMMENT ON COLUMN "CLUB_BOARD"."MATCH_FORM" IS '경기 형식';

COMMENT ON COLUMN "CLUB_BOARD"."MATERIAL" IS '준비물';

COMMENT ON COLUMN "CLUB_BOARD"."RECRUITMENT_DEADLINE" IS '모집마감시간';

COMMENT ON COLUMN "CLUB_BOARD"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "CLUB_BOARD"."UPDATE_TIME" IS '정보수정시간';


CREATE TABLE "FIELD_PIC" (
	"UUID"	VARCHAR2(255)		NOT NULL,
	"CLUB_BOARD_ID"	NUMBER		NOT NULL,
	"IMG_URL"	VARCHAR2(255)		NOT NULL,
	"IMG_FILE"	BLOB		NOT NULL
);

COMMENT ON COLUMN "FIELD_PIC"."UUID" IS '사진UUID';

COMMENT ON COLUMN "FIELD_PIC"."CLUB_BOARD_ID" IS '동아리게시판번호';

COMMENT ON COLUMN "FIELD_PIC"."IMG_URL" IS '이미지URL';

COMMENT ON COLUMN "FIELD_PIC"."IMG_FILE" IS '이미지파일';



CREATE TABLE "PARTICIPANTS" (
	"CLUB_BOARD_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"APPROVAL"	VARCHAR(255)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "PARTICIPANTS"."CLUB_BOARD_ID" IS '동아리게시판번호';

COMMENT ON COLUMN "PARTICIPANTS"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "PARTICIPANTS"."APPROVAL" IS '승인여부';

CREATE TABLE "NOTICE" (
	"NOTICE_ID"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(255)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"NOTICE_IMG"	BLOB		NULL,
	"NOTICE_ING_URL"	VARCHAR2(255)		NULL,
	"NOTICE_IMG_UUID"	VARCHAR2(255)		NULL,
	"EVENT_YN"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"EVENT_WINNER_QUOTA"	NUMBER	DEFAULT 0	NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_ID" IS '공지사항번호';

COMMENT ON COLUMN "NOTICE"."TITLE" IS '제목';

COMMENT ON COLUMN "NOTICE"."CONTENT" IS '내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_IMG" IS '공지사항이미지';

COMMENT ON COLUMN "NOTICE"."NOTICE_ING_URL" IS '공지사항이미지URL';

COMMENT ON COLUMN "NOTICE"."NOTICE_IMG_UUID" IS '공지사항이미지UUID';

COMMENT ON COLUMN "NOTICE"."EVENT_YN" IS '이벤트유무';

COMMENT ON COLUMN "NOTICE"."EVENT_WINNER_QUOTA" IS '이벤트당첨인원';

COMMENT ON COLUMN "NOTICE"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "NOTICE"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "DEPT_BOARD_REPORT" (
	"REPORT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"DEPT_BOARD_ID"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(255)		NOT NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "DEPT_BOARD_REPORT"."REPORT_ID" IS '신고번호';

COMMENT ON COLUMN "DEPT_BOARD_REPORT"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "DEPT_BOARD_REPORT"."DEPT_BOARD_ID" IS '부서게시판번호';

COMMENT ON COLUMN "DEPT_BOARD_REPORT"."CONTENT" IS '신고내용';

COMMENT ON COLUMN "DEPT_BOARD_REPORT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "DEPT_BOARD_REPORT"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "FREE_BOARD_RECOMMENT" (
	"FREE_BOARD_RECOMMENT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"FREE_BOARD_COMMENT_ID"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"SECRET_COMMENT_YN"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "FREE_BOARD_RECOMMENT"."FREE_BOARD_RECOMMENT_ID" IS '자유게시판댓글ID';

COMMENT ON COLUMN "FREE_BOARD_RECOMMENT"."USER_ID" IS '작성자';

COMMENT ON COLUMN "FREE_BOARD_RECOMMENT"."FREE_BOARD_COMMENT_ID" IS '자유게시판댓글ID';

COMMENT ON COLUMN "FREE_BOARD_RECOMMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "FREE_BOARD_RECOMMENT"."SECRET_COMMENT_YN" IS '비밀댓글유무';

COMMENT ON COLUMN "FREE_BOARD_RECOMMENT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "FREE_BOARD_RECOMMENT"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "DEPT_BOARD_RECOMMENT" (
	"DEPT_BOARD_RECOMMENT_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"DEPT_BOARD_COMMENT_ID"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"SECRET_COMMENT_YN"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"INSERT_TIME"	VARCHAR2(20)		NOT NULL,
	"UPDATE_TIME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "DEPT_BOARD_RECOMMENT"."DEPT_BOARD_RECOMMENT_ID" IS '부서게시판대댓글ID';

COMMENT ON COLUMN "DEPT_BOARD_RECOMMENT"."USER_ID" IS '작성자';

COMMENT ON COLUMN "DEPT_BOARD_RECOMMENT"."DEPT_BOARD_COMMENT_ID" IS '부서게시판댓글ID';

COMMENT ON COLUMN "DEPT_BOARD_RECOMMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "DEPT_BOARD_RECOMMENT"."SECRET_COMMENT_YN" IS '비밀댓글유무';

COMMENT ON COLUMN "DEPT_BOARD_RECOMMENT"."INSERT_TIME" IS '정보입력시간';

COMMENT ON COLUMN "DEPT_BOARD_RECOMMENT"."UPDATE_TIME" IS '정보수정시간';

CREATE TABLE "WINNER" (
	"WINNER_ID"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(16)		NOT NULL,
	"NOTICE_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "WINNER"."WINNER_ID" IS '당첨번호';

COMMENT ON COLUMN "WINNER"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "WINNER"."NOTICE_ID" IS '이벤트번호';

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "FREE_BOARD" ADD CONSTRAINT "PK_FREE_BOARD" PRIMARY KEY (
	"FREE_BOARD_ID"
);

ALTER TABLE "FREE_BOARD_COMMENT" ADD CONSTRAINT "PK_FREE_BOARD_COMMENT" PRIMARY KEY (
	"FREE_BOARD_COMMENT_ID"
);

ALTER TABLE "FREE_BOARD_REPORT" ADD CONSTRAINT "PK_FREE_BOARD_REPORT" PRIMARY KEY (
	"REPORT_ID"
);

ALTER TABLE "COMPLAINT_BOARD" ADD CONSTRAINT "PK_COMPLAINT_BOARD" PRIMARY KEY (
	"COMPLAINT_BOARD_ID"
);

ALTER TABLE "DEPARTMENT_BOARD" ADD CONSTRAINT "PK_DEPARTMENT_BOARD" PRIMARY KEY (
	"DEPT_BOARD_ID"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"DEPT_ID"
);

ALTER TABLE "COMPLAINT_BOARD_COMMENT" ADD CONSTRAINT "PK_COMPLAINT_BOARD_COMMENT" PRIMARY KEY (
	"FREE_BOARD_COMMENT_ID"
);

ALTER TABLE "DEPT_BOARD_COMMENT" ADD CONSTRAINT "PK_DEPT_BOARD_COMMENT" PRIMARY KEY (
	"DEPT_BOARD_COMMENT_ID"
);

ALTER TABLE "CLUB_BOARD" ADD CONSTRAINT "PK_CLUB_BOARD" PRIMARY KEY (
	"CLUB_BOARD_ID"
);

ALTER TABLE "FIELD_PIC" ADD CONSTRAINT "PK_FIELD_PIC" PRIMARY KEY (
	"UUID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_ID"
);

ALTER TABLE "DEPT_BOARD_REPORT" ADD CONSTRAINT "PK_DEPT_BOARD_REPORT" PRIMARY KEY (
	"REPORT_ID"
);

ALTER TABLE "FREE_BOARD_RECOMMENT" ADD CONSTRAINT "PK_FREE_BOARD_RECOMMENT" PRIMARY KEY (
	"FREE_BOARD_RECOMMENT_ID"
);

ALTER TABLE "DEPT_BOARD_RECOMMENT" ADD CONSTRAINT "PK_DEPT_BOARD_RECOMMENT" PRIMARY KEY (
	"DEPT_BOARD_RECOMMENT_ID"
);

ALTER TABLE "WINNER" ADD CONSTRAINT "PK_WINNER" PRIMARY KEY (
	"WINNER_ID"
);

ALTER TABLE "FREE_BOARD" ADD CONSTRAINT "FK_USER_TO_FREE_BOARD_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "FREE_BOARD_COMMENT" ADD CONSTRAINT "FK_USER_TO_FREE_BOARD_COMMENT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "FREE_BOARD_COMMENT" ADD CONSTRAINT "FK_FREE_BOARD_TO_FREE_BOARD_COMMENT_1" FOREIGN KEY (
	"FREE_BOARD_ID"
)
REFERENCES "FREE_BOARD" (
	"FREE_BOARD_ID"
);

ALTER TABLE "FREE_BOARD_REPORT" ADD CONSTRAINT "FK_USER_TO_FREE_BOARD_REPORT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "FREE_BOARD_REPORT" ADD CONSTRAINT "FK_FREE_BOARD_TO_FREE_BOARD_REPORT_1" FOREIGN KEY (
	"FREE_BOARD_ID"
)
REFERENCES "FREE_BOARD" (
	"FREE_BOARD_ID"
);

ALTER TABLE "COMPLAINT_BOARD" ADD CONSTRAINT "FK_USER_TO_COMPLAINT_BOARD_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "DEPARTMENT_BOARD" ADD CONSTRAINT "FK_USER_TO_DEPARTMENT_BOARD_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "DEPARTMENT_BOARD" ADD CONSTRAINT "FK_DEPARTMENT_TO_DEPARTMENT_BOARD_1" FOREIGN KEY (
	"DEPT_ID"
)
REFERENCES "DEPARTMENT" (
	"DEPT_ID"
);

ALTER TABLE "COMPLAINT_BOARD_COMMENT" ADD CONSTRAINT "FK_USER_TO_COMPLAINT_BOARD_COMMENT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "COMPLAINT_BOARD_COMMENT" ADD CONSTRAINT "FK_COMPLAINT_BOARD_TO_COMPLAINT_BOARD_COMMENT_1" FOREIGN KEY (
	"COMPLAINT_BOARD_ID"
)
REFERENCES "COMPLAINT_BOARD" (
	"COMPLAINT_BOARD_ID"
);

ALTER TABLE "DEPT_BOARD_COMMENT" ADD CONSTRAINT "FK_USER_TO_DEPT_BOARD_COMMENT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "DEPT_BOARD_COMMENT" ADD CONSTRAINT "FK_DEPARTMENT_BOARD_TO_DEPT_BOARD_COMMENT_1" FOREIGN KEY (
	"DEPT_BOARD_ID"
)
REFERENCES "DEPARTMENT_BOARD" (
	"DEPT_BOARD_ID"
);

ALTER TABLE "CLUB_BOARD" ADD CONSTRAINT "FK_USER_TO_CLUB_BOARD_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "FIELD_PIC" ADD CONSTRAINT "FK_CLUB_BOARD_TO_FIELD_PIC_1" FOREIGN KEY (
	"CLUB_BOARD_ID"
)
REFERENCES "CLUB_BOARD" (
	"CLUB_BOARD_ID"
);

ALTER TABLE "PARTICIPANTS" ADD CONSTRAINT "FK_CLUB_BOARD_TO_PARTICIPANTS_1" FOREIGN KEY (
	"CLUB_BOARD_ID"
)
REFERENCES "CLUB_BOARD" (
	"CLUB_BOARD_ID"
);

ALTER TABLE "PARTICIPANTS" ADD CONSTRAINT "FK_USER_TO_PARTICIPANTS_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "DEPT_BOARD_REPORT" ADD CONSTRAINT "FK_USER_TO_DEPT_BOARD_REPORT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "DEPT_BOARD_REPORT" ADD CONSTRAINT "FK_DEPARTMENT_BOARD_TO_DEPT_BOARD_REPORT_1" FOREIGN KEY (
	"DEPT_BOARD_ID"
)
REFERENCES "DEPARTMENT_BOARD" (
	"DEPT_BOARD_ID"
);

ALTER TABLE "FREE_BOARD_RECOMMENT" ADD CONSTRAINT "FK_USER_TO_FREE_BOARD_RECOMMENT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "FREE_BOARD_RECOMMENT" ADD CONSTRAINT "FK_FREE_BOARD_COMMENT_TO_FREE_BOARD_RECOMMENT_1" FOREIGN KEY (
	"FREE_BOARD_COMMENT_ID"
)
REFERENCES "FREE_BOARD_COMMENT" (
	"FREE_BOARD_COMMENT_ID"
);

ALTER TABLE "DEPT_BOARD_RECOMMENT" ADD CONSTRAINT "FK_USER_TO_DEPT_BOARD_RECOMMENT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "DEPT_BOARD_RECOMMENT" ADD CONSTRAINT "FK_DEPT_BOARD_COMMENT_TO_DEPT_BOARD_RECOMMENT_1" FOREIGN KEY (
	"DEPT_BOARD_COMMENT_ID"
)
REFERENCES "DEPT_BOARD_COMMENT" (
	"DEPT_BOARD_COMMENT_ID"
);

ALTER TABLE "WINNER" ADD CONSTRAINT "FK_USER_TO_WINNER_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "USER" (
	"USER_ID"
);

ALTER TABLE "WINNER" ADD CONSTRAINT "FK_NOTICE_TO_WINNER_1" FOREIGN KEY (
	"NOTICE_ID"
)
REFERENCES "NOTICE" (
	"NOTICE_ID"
);

